name: Abdocare-Web-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
        flutter-version: '1.23.0-18.1.pre' 
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
