name: Abdocare-Web-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: stable
        flutter-version: '2.2.3' 
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
